highlighter: pygments
markdown: redcarpet
#Default YAML fronmatter settings
# defaults:
#  - scope: 
#  -  path: ""
#  - type: "posts"

#Setup:
title: Dontry Blog
# baseurl: /dontry.github.io
source: .
destination: ./_site
layouts: ./_layouts
plugins: ./_plugins
paginate: 4
safe: true
lsi: false
repository: https://github.com/dontry/dontry.github.io
help_url: https://github.com/jekyll/jekyll-help
timezone: Asia/Shanghai
keep_files: ["images"]
exclude: [node_modules]

#RSS
name: Dontry
description: my first personal blog
url: http://dontry.github.io


#Profile
author:  Dontry
e-mail: mccoy018@gmail.com

#Permalinks:
relative_permalinks: true
permalink: pretty #/news/:year/:month/:day/:title/

#Conversion
excerpt_separator: "<!-- excerpt -->"

# gauges_id: 503c5af6613f5d0f19000027
# google_analytics_id: UA-50755011-1



