markdown: kramdown
highlighter: pygments
safe: true
lsi: false
baseurl: dontry.github.io
# permalink: /news/:year/:month/:day/:title/
# excerpt_separator: ""

# gauges_id: 503c5af6613f5d0f19000027
# google_analytics_id: UA-50755011-1
# baseurl: /dontry.github.io

repository: https://github.com/dontry/dontry.github.io
help_url: https://github.com/jekyll/jekyll-help
safe: true
lsi: false
source: dontry.github.io
# collections:
#   docs:
#     output: true

