highlighter: pygments

#Default YAML fronmatter settings
# defaults:
#   -
#     scope: 
#      path: ""
#      type: "posts"
#      values:


#Setup:
title: Dontry Blog
url: dontry.github.io
# baseurl: /dontry.github.io
source: /Users/caidong/Documents/Web_Design/dontry_blog/dontry.github.io
paginate: 4
safe: true
lsi: false
repository: https://github.com/dontry/dontry.github.io
help_url: https://github.com/jekyll/jekyll-help
timezone: Asia/Shanghai

#RSS
name: Dontry
description: my first personal blog
url: http://dontry.github.io


#Profile
author:  Dontry
e-mail: mccoy018@gmail.com

#Permalinks:
# permalink: pretty #/news/:year/:month/:day/:title/

#Conversion
markdown: kramdown
excerpt_separator: "<!-- excerpt -->"

# gauges_id: 503c5af6613f5d0f19000027
# google_analytics_id: UA-50755011-1


