
highlighter: pygments

#Default YAML fronmatter settings
defaults:
  -
    scope: 
     path: ""
     type: "posts"
     values:
     comments:true


#Setup:
title: Dontry Blog
url: dontry.githu.io
baseurl: "/dontry.github.io"
paginate: 5
safe: true
lsi: false
repository: https://github.com/dontry/dontry.github.io
help_url: https://github.com/jekyll/jekyll-help

#Permalinks:
permalink: /news/:year/:month/:day/:title/

#Conversion
markdown: kramdown
excerpt_separator: "<!-- excerpt -->"

# gauges_id: 503c5af6613f5d0f19000027
# google_analytics_id: UA-50755011-1


